"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, FileSpreadsheet, ShieldCheck, Table2, UploadCloud, X } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { GlassCard } from "@/components/ui/glass-card";
import { uploadDataset } from "@/lib/api";
import { demoUpload } from "@/lib/mock-data";

export default function UploadPage(){
 const router=useRouter(); const input=useRef<HTMLInputElement>(null); const [file,setFile]=useState<File|null>(null); const [drag,setDrag]=useState(false); const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(0); const [error,setError]=useState<string|null>(null);
 const choose=(f?:File)=>{if(!f)return;setError(null);if(!/\.(csv|xlsx)$/i.test(f.name)){setError("Choose a CSV or XLSX file.");return} if(f.size>25*1024*1024){setError("Maximum file size is 25 MB.");return} setFile(f)};
 const run=async()=>{if(!file)return;setBusy(true);setError(null);let p=8;setProgress(p);const timer=setInterval(()=>{p=Math.min(p+Math.random()*13,86);setProgress(p)},180);try{const data=await uploadDataset(file);localStorage.setItem("insightflow.dataset",JSON.stringify(data));setProgress(100);setTimeout(()=>router.push('/preview'),220)}catch(e){setError(e instanceof Error?e.message:"Upload failed.");}finally{clearInterval(timer);setBusy(false)}};
 const demo=()=>{localStorage.setItem("insightflow.dataset",JSON.stringify(demoUpload));router.push('/preview')};
 return <><PageHeader eyebrow="Data ingestion" title="Bring your data into focus." description="Upload a sales dataset. InsightFlow inspects structure before it calculates a single metric."/>
 <div className="upload-layout reveal delay-1"><GlassCard className={`upload-zone ${drag?"dragging":""}`}><div className="upload-inner" onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files[0])}} onClick={()=>!file&&input.current?.click()}><input ref={input} hidden type="file" accept=".csv,.xlsx" onChange={e=>choose(e.target.files?.[0])}/>{!file?<><div className="upload-orb"><UploadCloud size={31}/><span/></div><div className="eyebrow"><span/>Import</div><h2>Drop your dataset here</h2><p>CSV or Excel, up to 25 MB. Your schema is inspected locally by the API before analytics.</p><button className="button primary" type="button" onClick={e=>{e.stopPropagation();input.current?.click()}}>Choose a file</button><small>or drag and drop anywhere inside this panel</small></>:<div className="selected-file"><div className="file-icon"><FileSpreadsheet size={28}/></div><div className="selected-copy"><small>Selected file</small><h3>{file.name}</h3><p>{(file.size/1024/1024).toFixed(2)} MB · {file.name.toLowerCase().endsWith('xlsx')?'Excel workbook':'CSV dataset'}</p></div><button className="icon-button" onClick={e=>{e.stopPropagation();setFile(null)}}><X size={17}/></button></div>}</div>{busy&&<div className="upload-progress"><div><span>Inspecting dataset…</span><strong>{Math.round(progress)}%</strong></div><div className="progress-track"><i style={{width:`${progress}%`}}/></div></div>}{error&&<div className="inline-error">{error}</div>}{file&&!busy&&<div className="upload-actions"><button className="button glass" onClick={()=>setFile(null)}>Choose another</button><button className="button primary" onClick={run}>Inspect dataset <ArrowRight size={16}/></button></div>}</GlassCard>
 <div className="upload-side"><GlassCard className="demo-card"><div className="demo-icon"><Table2 size={20}/></div><div><div className="eyebrow"><span/>No file handy?</div><h3>Explore with retail demo data.</h3><p>A realistic sales dataset is bundled with the project so anyone reviewing your portfolio can see the complete flow instantly.</p></div><button className="button glass full" onClick={demo}>Load demo dataset <ArrowRight size={16}/></button></GlassCard><GlassCard className="security-card"><div className="card-heading compact"><div><h3>What happens next</h3><p>Transparent by design.</p></div><ShieldCheck size={20}/></div><ol className="step-list">{[["01","Schema inspection","Column names, types and sample values."],["02","Semantic mapping","Revenue, date, product and business fields."],["03","Quality scan","Duplicates, missing values and anomalies."],["04","Analytics","Metrics only after you confirm the mapping."]].map(s=><li key={s[0]}><span>{s[0]}</span><div><strong>{s[1]}</strong><small>{s[2]}</small></div><Check size={14}/></li>)}</ol></GlassCard></div></div></>}
