"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, Check, CheckCircle2, DatabaseZap, Info, ShieldCheck } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { GlassCard } from "@/components/ui/glass-card";
import { demoQuality } from "@/lib/mock-data";
import type { QualityResponse } from "@/lib/types";

export default function QualityPage(){const [q,setQ]=useState<QualityResponse>(demoQuality);useEffect(()=>{const s=localStorage.getItem('insightflow.quality');if(s)try{setQ(JSON.parse(s))}catch{}},[]);return <><PageHeader eyebrow="Data quality" title="Quality overview" description="Structural checks and warnings before the dataset is used for analytics."/><div className="quality-layout reveal delay-1"><GlassCard className="score-card"><div className="score-visual"><svg viewBox="0 0 180 180"><circle className="score-track" cx="90" cy="90" r="70"/><circle className="score-ring" cx="90" cy="90" r="70" pathLength="100" strokeDasharray={`${q.score} ${100-q.score}`}/></svg><div className="score-center"><strong>{q.score}</strong><span>/100</span></div></div><div className="score-copy"><div className="eyebrow"><span/>Quality score</div><h2>{q.grade}</h2><p>Critical fields are usable. Remaining issues are low risk and fully disclosed below.</p></div><div className="score-meta"><span><small>Rows scanned</small>{q.rows.toLocaleString()}</span><span><small>Columns</small>{q.columns}</span><span><small>Issues</small>{q.issues.length}</span></div></GlassCard><GlassCard className="healthy-card"><div className="card-heading compact"><div><h3>Checks without issues</h3><p>No problems were found in these areas.</p></div><ShieldCheck size={20}/></div><div className="healthy-list">{q.healthy_checks.map(v=><div key={v}><span><Check size={14}/></span>{v}</div>)}</div></GlassCard></div><GlassCard className="issues-card reveal delay-2"><div className="card-heading"><div><h2>Reviewable issues</h2><p>Every score deduction has a concrete reason.</p></div><span className="deduction-pill">-{q.issues.reduce((a,b)=>a+b.deduction,0)} pts total</span></div><div className="issue-list">{q.issues.map(issue=><div className="issue-row" key={issue.code}><div className={`issue-icon ${issue.severity}`} >{issue.severity==='high'?<AlertTriangle size={18}/>:issue.severity==='medium'?<DatabaseZap size={18}/>:<Info size={18}/>}</div><div className="issue-copy"><div><strong>{issue.title}</strong><span className={`severity ${issue.severity}`}>{issue.severity}</span></div><p>{issue.detail}</p></div><div className="issue-numbers"><strong>{issue.count}</strong><small>rows</small></div><div className="issue-deduction">-{issue.deduction}</div></div>)}</div></GlassCard><div className="quality-cta glass-card reveal delay-3"><div><span className="quality-cta-icon"><CheckCircle2/></span><div><strong>Continue with this dataset</strong><p>Quality warnings remain visible as context while you explore the analytics.</p></div></div><Link className="button primary large" href="/dashboard">Open analytics <ArrowRight size={17}/></Link></div></>}
