"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronDown, Columns3, Database, FileSpreadsheet } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { GlassCard } from "@/components/ui/glass-card";
import { analyzeDataset, getQuality } from "@/lib/api";
import { demoAnalytics, demoQuality, demoUpload } from "@/lib/mock-data";
import type { UploadResponse } from "@/lib/types";

const roles=[['date','Order date','When the transaction happened'],['revenue','Revenue','Final revenue or line total'],['order_id','Order ID','Unique transaction identifier'],['customer','Customer','Customer or account identifier'],['product','Product','Product or SKU name'],['category','Category','Product grouping'],['region','Region','Location or market'],['quantity','Quantity','Units sold'],['unit_price','Unit price','Price before multiplication']];
export default function PreviewPage(){const router=useRouter();const [data,setData]=useState<UploadResponse>(demoUpload);const [currency,setCurrency]=useState('EUR');const [running,setRunning]=useState(false);const [mapping,setMapping]=useState<Record<string,string>>({});
 useEffect(()=>{const saved=localStorage.getItem('insightflow.dataset');if(saved){try{const parsed=JSON.parse(saved) as UploadResponse;setData(parsed)}catch{}}},[]);
 useEffect(()=>{const m:Record<string,string>={};Object.entries(data.detected_mapping).forEach(([role,v])=>m[role]=v.column);setMapping(m)},[data]);
 const mappedCount=useMemo(()=>Object.values(mapping).filter(Boolean).length,[mapping]);
 const proceed=async()=>{setRunning(true);localStorage.setItem('insightflow.mapping',JSON.stringify(mapping));localStorage.setItem('insightflow.currency',currency);try{if(data.dataset_id==='demo-retail'){localStorage.setItem('insightflow.quality',JSON.stringify(demoQuality));localStorage.setItem('insightflow.analytics',JSON.stringify(demoAnalytics));}else{const [q,a]=await Promise.all([getQuality(data.dataset_id,mapping),analyzeDataset(data.dataset_id,mapping)]);localStorage.setItem('insightflow.quality',JSON.stringify(q));localStorage.setItem('insightflow.analytics',JSON.stringify(a));}router.push('/quality')}catch(e){alert(e instanceof Error?e.message:'Analysis failed')}finally{setRunning(false)}};
 return <><PageHeader eyebrow="Semantic mapping" title="Tell InsightFlow what your columns mean." description={`${data.filename} · ${data.rows.toLocaleString()} rows · ${data.columns.length} columns`} actions={<div className="confidence-pill"><CheckCircle2 size={15}/>{mappedCount} fields mapped</div>}/>
 <div className="preview-grid reveal delay-1"><GlassCard className="mapping-panel"><div className="card-heading"><div><h2>Business fields</h2><p>Mappings decouple source column names from analytics logic.</p></div><div className="mapping-score"><span>Suggested mappings</span></div></div><div className="mapping-table">{roles.map(([role,label,help])=>{const d=data.detected_mapping[role];return <div className="mapping-item" key={role}><div className="mapping-role"><strong>{label}</strong><small>{help}</small></div><div className="select-wrap"><select value={mapping[role]??''} onChange={e=>setMapping(v=>({...v,[role]:e.target.value}))}><option value="">Not mapped</option>{data.columns.map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={15}/></div><span className={`confidence ${d?.confidence>=.9?'high':d?'medium':'none'}`}>{d?`${Math.round(d.confidence*100)}%`:'—'}</span></div>})}</div></GlassCard>
 <div className="preview-side"><GlassCard className="dataset-meta"><div className="file-badge"><FileSpreadsheet size={22}/></div><div><div className="eyebrow"><span/>Source dataset</div><h3>{data.filename}</h3><p>{data.rows.toLocaleString()} records · {data.columns.length} source columns</p></div><div className="dataset-meta-row"><span><Database size={15}/>Dataset ID</span><code>{data.dataset_id.slice(0,12)}</code></div><div className="dataset-meta-row"><span>Currency</span><select value={currency} onChange={e=>setCurrency(e.target.value)}><option>EUR</option><option>USD</option><option>GBP</option><option>CZK</option></select></div></GlassCard><GlassCard className="mapping-note"><Columns3 size={18}/><div><strong>Why mapping matters</strong><p>Analytics asks for <code>revenue</code>, not <code>total_price</code>. That keeps the engine reusable across completely different source systems.</p></div></GlassCard></div></div>
 <GlassCard className="data-preview reveal delay-2"><div className="card-heading"><div><h2>Data preview</h2><p>The first {Math.min(data.preview.length,20)} rows, unchanged from source.</p></div><span className="small-muted">{data.columns.length} columns</span></div><div className="table-scroll"><table className="premium-table"><thead><tr>{data.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{data.preview.map((row,i)=><tr key={i}>{data.columns.map(c=><td key={c}>{String(row[c]??'—')}</td>)}</tr>)}</tbody></table></div></GlassCard>
 <div className="sticky-actions"><button className="button glass" onClick={()=>router.push('/upload')}><ArrowLeft size={16}/> Back</button><div><span>{mapping.revenue?'Revenue field mapped':'Map a revenue field to continue'}</span><button className="button primary" disabled={!mapping.revenue||running} onClick={proceed}>{running?'Analyzing…':'Run quality scan'} <ArrowRight size={16}/></button></div></div></>}
